/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.21.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.trabajott1.api;

import org.trabajott1.model.EmailResponse;
import org.springframework.lang.Nullable;
import org.trabajott1.model.ProblemDetails;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import jakarta.annotation.Generated;

/**
 * Interfaz que define el contrato del endpoint de envío de correo electrónico.
 * Generada automáticamente por OpenAPI Generator a partir del contrato de la API.
 * La implementación real de la lógica se hace en {@link EmailApiDelegate}.
 *
 * @author Lucas, Ana, Clara, Santiago
 * @version 1.0
 */
@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-04-14T15:27:37.393153+02:00[Europe/Madrid]", comments = "Generator version: 7.21.0")
@Validated
@Tag(name = "Email", description = "the Email API")
public interface EmailApi {

    /**
     * Devuelve el delegado que implementa la lógica del endpoint.
     * Por defecto devuelve una implementación vacía.
     *
     * @return el {@link EmailApiDelegate} activo
     * @author Lucas, Ana, Clara, Santiago
     * @version 1.0
     */
    default EmailApiDelegate getDelegate() {
        return new EmailApiDelegate() {};
    }

    /** Ruta del endpoint para envío de correo electrónico. */
    String PATH_EMAIL_POST = "/Email";

    /**
     * Envía un correo electrónico al destinatario indicado con el mensaje proporcionado.
     *
     * @param emailAddress la dirección de correo del destinatario (opcional)
     * @param message      el contenido del mensaje a enviar (opcional)
     * @return código 201 si el correo se envió correctamente, o 400 si los datos son incorrectos
     * @author Lucas, Ana, Clara, Santiago
     * @version 1.0
     */
    @Operation(
        operationId = "emailPost",
        tags = { "Email" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Created", content = {
                @Content(mediaType = "text/plain", schema = @Schema(implementation = EmailResponse.class)),
                @Content(mediaType = "application/json", schema = @Schema(implementation = EmailResponse.class)),
                @Content(mediaType = "text/json", schema = @Schema(implementation = EmailResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "text/plain", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "text/json", schema = @Schema(implementation = ProblemDetails.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = EmailApi.PATH_EMAIL_POST,
        produces = { "text/plain", "application/json", "text/json" }
    )
    default ResponseEntity<EmailResponse> emailPost(
        @Parameter(name = "emailAddress", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "emailAddress", required = false) @Nullable String emailAddress,
        @Parameter(name = "message", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "message", required = false) @Nullable String message
    ) {
        return getDelegate().emailPost(emailAddress, message);
    }

}
