/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.21.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.trabajott1.api;

import org.trabajott1.model.EmailResponse;
import org.springframework.lang.Nullable;
import org.trabajott1.model.ProblemDetails;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-04-14T15:27:37.393153+02:00[Europe/Madrid]", comments = "Generator version: 7.21.0")
@Validated
@Tag(name = "Email", description = "the Email API")
public interface EmailApi {

    default EmailApiDelegate getDelegate() {
        return new EmailApiDelegate() {};
    }

    String PATH_EMAIL_POST = "/Email";
    /**
     * POST /Email
     *
     * @param emailAddress  (optional)
     * @param message  (optional)
     * @return Created (status code 201)
     *         or Bad Request (status code 400)
     */
    @Operation(
        operationId = "emailPost",
        tags = { "Email" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Created", content = {
                @Content(mediaType = "text/plain", schema = @Schema(implementation = EmailResponse.class)),
                @Content(mediaType = "application/json", schema = @Schema(implementation = EmailResponse.class)),
                @Content(mediaType = "text/json", schema = @Schema(implementation = EmailResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "text/plain", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "text/json", schema = @Schema(implementation = ProblemDetails.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = EmailApi.PATH_EMAIL_POST,
        produces = { "text/plain", "application/json", "text/json" }
    )
    default ResponseEntity<EmailResponse> emailPost(
        @Parameter(name = "emailAddress", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "emailAddress", required = false) @Nullable String emailAddress,
        @Parameter(name = "message", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "message", required = false) @Nullable String message
    ) {
        return getDelegate().emailPost(emailAddress, message);
    }

}
