/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.21.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.trabajott1.api;

import org.springframework.lang.Nullable;
import org.trabajott1.model.ProblemDetails;
import org.trabajott1.model.ResultsResponse;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-04-14T15:27:37.393153+02:00[Europe/Madrid]", comments = "Generator version: 7.21.0")
@Validated
@Tag(name = "Resultados", description = "the Resultados API")
public interface ResultadosApi {

    default ResultadosApiDelegate getDelegate() {
        return new ResultadosApiDelegate() {};
    }

    String PATH_RESULTADOS_POST = "/Resultados";
    /**
     * POST /Resultados
     *
     * @param nombreUsuario  (optional)
     * @param tok  (optional)
     * @return Created (status code 201)
     *         or Bad Request (status code 400)
     */
    @Operation(
        operationId = "resultadosPost",
        tags = { "Resultados" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Created", content = {
                @Content(mediaType = "text/plain", schema = @Schema(implementation = ResultsResponse.class)),
                @Content(mediaType = "application/json", schema = @Schema(implementation = ResultsResponse.class)),
                @Content(mediaType = "text/json", schema = @Schema(implementation = ResultsResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "text/plain", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "text/json", schema = @Schema(implementation = ProblemDetails.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ResultadosApi.PATH_RESULTADOS_POST,
        produces = { "text/plain", "application/json", "text/json" }
    )
    default ResponseEntity<ResultsResponse> resultadosPost(
        @Parameter(name = "nombreUsuario", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "nombreUsuario", required = false) @Nullable String nombreUsuario,
        @Parameter(name = "tok", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "tok", required = false) @Nullable Integer tok
    ) {
        return getDelegate().resultadosPost(nombreUsuario, tok);
    }

}
